    - &Orgname
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: OrgnameMSP

        # ID to load the MSP definition as
        ID: OrgnameMSP

        MSPDir: ../organizations/peerOrganizations/orgname.example.com/msp

        # Policies defines the set of policies at this level of the config tree
        # For organization policies, their canonical path is usually
        #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrgnameMSP.admin', 'OrgnameMSP.peer', 'OrgnameMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('OrgnameMSP.admin', 'OrgnameMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('OrgnameMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('OrgnameMSP.peer')"
