  
  peernumber.orgname.example.com:
    container_name: peernumber.orgname.example.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker_networkname
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peernumber.orgname.example.com
      - CORE_PEER_ADDRESS=peernumber.orgname.example.com:portpeer
      - CORE_PEER_LISTENADDRESS=0.0.0.0:portpeer
      - CORE_PEER_CHAINCODEADDRESS=peernumber.orgname.example.com:portpeer2
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:portpeer2
      - CORE_PEER_GOSSIP_BOOTSTRAP=peernumber.orgname.example.com:portpeer
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peernumber.orgname.example.com:portpeer
      - CORE_PEER_LOCALMSPID=OrgnameMSP
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../organizations/peerOrganizations/orgname.example.com/peers/peernumber.orgname.example.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/orgname.example.com/peers/peernumber.orgname.example.com/tls:/etc/hyperledger/fabric/tls
        - peernumber.orgname.example.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - portpeer:portpeer
    networks:
      - networkname
